# Generated by Django 4.2 on 2023-04-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_question_question_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="choice", unique_together={("question", "choice_text")},
        ),
    ]
